version: "3.8"

services:
  app:
    build: .
    container_name: dotnet_app
    depends_on:
      - db
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=mydatabase;Username=myuser;Password=mypassword
    networks:
      - backend
    expose:
      - "8080"
    entrypoint: ["/bin/sh", "-c", "sleep 10 && dotnet Example.dll"]  # Wait 10 sec before running

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: exampledb  # Changed to match appsettings.json
      POSTGRES_USER: exampleuser  # Changed to match appsettings.json
      POSTGRES_PASSWORD: examplepass  # Changed to match appsettings.json
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
