version: '3.8'

services:
  #  ASP.NET 
  web:
    build: .
    container_name: aspnet-app
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__ProductionConnection: Host=db;Database=exampledb;Username=exampleuser;Password=examplepass
    depends_on:
      - db
    networks:
      - backend

  # PostgreSQL database container
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - backend

  # Reverse proxy for HTTPS (Caddy)
  proxy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"   # HTTP traffic
      - "443:443" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile 
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
