caddy:
  image: caddy:latest
  container_name: caddy_proxy
  restart: always
  ports:
    - "80:80"    # HTTP traffic (redirect to HTTPS)
    - "443:443"  # HTTPS traffic
  volumes:
    - caddy_data:/data
    - caddy_config:/config
    - ./Caddyfile:/etc/caddy/Caddyfile  # Mount your Caddyfile for configuration
  depends_on:
    - app  # Ensure the app is up before Caddy
  networks:
    - backend  # Same backend network as other services for communication