version: '3.8'

services:
  web:
    build: .
    container_name: aspnet-app
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__ProductionConnection: Host=db;Database=exampledb;Username=exampleuser;Password=examplepass
    depends_on:
      - db
      - proxy

  db:
    image: postgres:16  # Consider switching to postgres:14 if issues persist
    container_name: postgres-db
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  proxy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Caddy configuration

volumes:
  postgres_data:
